# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Terraform'
              backendServiceArm: 'CMEADOWS-ADO-SP'
              backendAzureRmResourceGroupName: 'ado-tf-test'
              backendAzureRmStorageAccountName: 'adobackend029390'
              backendAzureRmContainerName: 'tfbackend'
              backendAzureRmKey: 'EVgq3C4uLs2MJld25Df9kD/NjcGL9XgnBRI1YEN6UyyIC1LEYA5rAMIsHPR39850THC8QhimslSx+AStPyy8lA=='

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Terraform'